version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=sagemaker,bedrock,comprehend,lex,kendra,personalize
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"